name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install .NET workloads
        run: dotnet workload restore SDL3-CS/SDL3-CS.csproj

      - name: Build & pack
        run: dotnet pack SDL3-CS/SDL3-CS.csproj -c Release /p:Version=$(git describe --exact-match --tags HEAD)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDL3-CS
          path: SDL3-CS/bin/Release/ppy.*.nupkg

      - name: Publish tagged release to nuget.org
        run: dotnet nuget push SDL3-CS/bin/Release/ppy.*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
